name: CI
on: [push]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby: [ 2.5, 2.6, 2.7 ]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - run: gem install bundler -v 1.17.2
    - run: BUNDLER_VERSION=1.17.2 bundle
    - run: rake
